### ISSUE TITLE
secret key/values not injecting into workflows

### ISSUE THREAD

**Issue by daba-sharhan** [abhilash1in/aws-secrets-manager-action#29]
I am trying to inject `key/values` from aws secret manager with a secret name `test/secret`. I realize the values are not being injected into the environment variables. This is my sample code to retrieve a `token` value

```
- name: Read secrets from AWS Secrets Manager into environment variables
      uses: abhilash1in/aws-secrets-manager-action@v1.1.0
      id: read-secrets
      with:
        secrets: |
          test/secret
        parse-json: true

    - name: Check if env variable is set after fetching secrets
      run: | 
        echo "value is ${token}"
```
